packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zod: '^4.3.6'
