export const BOOKING_STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  TRAVELLING: 'travelling',
  ARRIVED: 'arrived',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  DISPUTED: 'disputed',
} as const;

export type BookingStatusValue = (typeof BOOKING_STATUS)[keyof typeof BOOKING_STATUS];

export const VALID_STATUS_TRANSITIONS: Record<string, string[]> = {
  [BOOKING_STATUS.PENDING]: [BOOKING_STATUS.ACCEPTED, BOOKING_STATUS.REJECTED],
  [BOOKING_STATUS.ACCEPTED]: [BOOKING_STATUS.TRAVELLING],
  [BOOKING_STATUS.TRAVELLING]: [BOOKING_STATUS.ARRIVED],
  [BOOKING_STATUS.ARRIVED]: [BOOKING_STATUS.IN_PROGRESS],
  [BOOKING_STATUS.IN_PROGRESS]: [BOOKING_STATUS.COMPLETED],
};

export const CANCELLABLE_STATUSES: string[] = [
  BOOKING_STATUS.PENDING,
  BOOKING_STATUS.ACCEPTED,
  BOOKING_STATUS.TRAVELLING,
];

export const COMPLETION_PHOTO_STATUSES: string[] = [
  BOOKING_STATUS.IN_PROGRESS,
  BOOKING_STATUS.COMPLETED,
];

export const MAX_COMPLETION_PHOTOS = 5;
